name: Java Maven Template GitHub Action

on:
  workflow_call:
    inputs:
      deploy:
        required: true
        type: boolean
      app-name:
        required: true
        type: string
    secrets:
      azure-credentials:
        required: true
      github-token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      - name: Configure Maven settings for GitHub Packages
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>JoseOrihuelaR</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build and package Quarkus application
        run: |
          # Este comando compila y empaqueta tu aplicación Quarkus.
          # Asegúrate de que tu pom.xml tiene el plugin de Quarkus configurado.
          # '-DskipTests' se usa para saltar los tests y acelerar el build en CI.
          mvn clean install -DskipTests

      - name: List generated files in target
        run: |
          echo "Listing files in target/ directory:"
          ls -l target/

      - name: Find Quarkus Runner JAR
        id: find_jar
        run: |
          # Busca el JAR principal de la aplicación Quarkus.
          # Quarkus generalmente genera un JAR ejecutable con '-runner.jar' o lo coloca en 'quarkus-app/'.
          # Ajusta este patrón si el nombre de tu artefacto es diferente.
          JAR_PATH=$(find target -name "*-runner.jar" | head -n 1)
          if [ -z "$JAR_PATH" ]; then
            JAR_PATH=$(find target/quarkus-app -name "*.jar" | head -n 1)
          fi
          if [ -z "$JAR_PATH" ]; then
            echo "Error: No Quarkus runner JAR found in target/ or target/quarkus-app/"
            exit 1
          fi
          echo "Found Quarkus JAR: $JAR_PATH"
          # Exporta la ruta del JAR para que esté disponible en pasos posteriores
          echo "quarkus_jar_path=$JAR_PATH" >> $GITHUB_ENV

      - name: Upload Quarkus JAR for deployment
        uses: actions/upload-artifact@v4
        with:
          name: quarkus-app
          path: ${{ env.quarkus_jar_path }}
          retention-days: 5

  deploy:
    if: ${{ inputs.deploy }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Quarkus JAR
        uses: actions/download-artifact@v4
        with:
          name: quarkus-app
          path: ./artifacts # El JAR se descargará en el directorio ./artifacts/

      - name: List files in artifacts directory
        run: |
          echo "Listing files in ./artifacts directory:"
          ls -l ./artifacts/

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure-credentials }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2 # ¡Este es el action correcto para Azure Web Apps!
        with:
          app-name: ${{ inputs.app-name }}
          slot-name: "production"
          package: ./artifacts/*.jar
