name: Java Quarkus Build and Deploy

on:
  workflow_call:
    inputs:
      deploy:
        required: true
        type: boolean
      app-name:
        required: true
        type: string
    secrets:
      azure-credentials:
        required: true
      github-token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      - name: Build Quarkus app
        run: mvn clean install -DskipTests

      - name: Locate generated JAR
        id: find_jar
        run: |
          echo "🔍 Buscando archivo JAR..."
          JAR_PATH=$(find target -type f -name "*.jar" | grep -v 'original' | head -n 1)

          if [ -z "$JAR_PATH" ]; then
            echo "❌ No se encontró ningún archivo .jar en target/"
            exit 1
          fi

          echo "✅ JAR encontrado: $JAR_PATH"
          echo "quarkus_jar_path=$JAR_PATH" >> $GITHUB_ENV

      - name: Subir JAR como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: quarkus-app
          path: ${{ env.quarkus_jar_path }}
          retention-days: 3

  deploy:
    if: ${{ inputs.deploy }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Descargar JAR desde artefacto
        uses: actions/download-artifact@v4
        with:
          name: quarkus-app
          path: ./artifacts

      - name: Verificar que el JAR existe
        run: |
          echo "📂 Archivos en ./artifacts:"
          ls -lh ./artifacts

          JAR_FILE=$(find ./artifacts -type f -name "*.jar" | head -n 1)
          if [ -z "$JAR_FILE" ]; then
            echo "❌ ERROR: No se encontró ningún archivo .jar en ./artifacts/"
            exit 1
          fi
          echo "✅ Archivo para desplegar: $JAR_FILE"
          echo "deploy_jar=$JAR_FILE" >> $GITHUB_ENV

      - name: Iniciar sesión en Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure-credentials }}

      - name: Desplegar en Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.app-name }}
          slot-name: "production"
          package: ${{ env.deploy_jar }}
